name: Movie-Search-Assignment 


on:
  push:
    branches: 
      - master


jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./movie-search-assignment

      - name: Run tests
        # For example, using `pytest`
        run: pytest tests
        working-directory: ./movie-search-assignment
